name: Run PR Checks
on:
  push:
    branches:
      - master
      - v2
      - "v2-*"
      - "feature/**"
  pull_request:
    branches:
      - master
      - v2
      - "feature/**"
jobs:
  prcheck:
    runs-on: ${{ matrix.os }}
    env:
      HYPOTHESIS_PROFILE: ci
      CHALICE_TEST_EXTENDED_PACKAGING: true
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Set up Python ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install a specific version of uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.20"
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Run PRCheck
        run: uv run make prcheck